version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://neda:pass@db:5432/articledb?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: neda
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: articledb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./repository/db/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
